version: '2'
services:
  library:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 80:7000
    volumes:
     - .:/home/app/testes-automatizados
     - /home/app/testes-automatizados/node_modules
